### ISSUE TITLE
get_characters() unicode_name can be undefined

### ISSUE THREAD

**Issue by seproDev** [fabiocaccamo/python-fontbro#51]
**Python version**
3.10.9

**Package version**
0.14.4

**Current behavior (bug description)**
In `get_characters()`, `unicode_name` can be undefined causing a crash. Here, an example font
[ANASTCN.zip](https://github.com/fabiocaccamo/python-fontbro/files/10514759/ANASTCN.zip) causing the crash on calling `get_characters_count()`.

Stacktrace:
```
Traceback (most recent call last):
  File "C:\Users\User\Desktop\fonts\main.py", line 30, in <module>
    main()
  File "C:\Users\User\Desktop\fonts\main.py", line 23, in main
    analyze_font("ANASTCN.ttf")
  File "C:\Users\User\Desktop\fonts\analyze_font.py", line 82, in analyze_font
    result["character_count"] = font.get_characters_count()
  File "C:\Users\User\AppData\Local\Programs\Python\Python310\lib\site-packages\fontbro\font.py", line 311, in get_characters_count
    return len(list(self.get_characters(ignore_blank=ignore_blank)))
  File "C:\Users\User\AppData\Local\Programs\Python\Python310\lib\site-packages\fontbro\font.py", line 295, in get_characters      
    "unicode_name": unicode_name,
UnboundLocalError: local variable 'unicode_name' referenced before assignment
```
The characters also seem to be incorrectly mapped, but I think that is an issue with the font, as fontforge shows the same incorrect mapping (though it is fine on regular use in Windows).

**Comment by fabiocaccamo** [comment]
Fixed in `0.14.5` version.
