### ISSUE TITLE
Crash when glyph outside Unicode range

### ISSUE THREAD

**Issue by seproDev** [fabiocaccamo/python-fontbro#52]
**Python version**
3.10.9

**Package version**
0.14.4

**Current behavior (bug description)**
Fonts my contain glyphs outside the defined Unicode range. For example, [Bobbiefreebie.ttf](https://github.com/fabiocaccamo/python-fontbro/files/10514999/Bobbiefreebie.zip) contains the ligature glyphs outside the defined range, causing `chr()` to throw an exception when calling `get_characters_count()`:
```
Traceback (most recent call last):
  File "C:\Users\User\Desktop\fonts\main.py", line 31, in <module>
    main()
  File "C:\Users\User\Desktop\fonts\main.py", line 23, in main
    result = analyze_font("Bobbiefreebie.ttf")
  File "C:\Users\User\Desktop\fonts\analyze_font.py", line 95, in analyze_font
    result["character_count"] = font.get_characters_count()
  File "C:\Users\User\AppData\Local\Programs\Python\Python310\lib\site-packages\fontbro\font.py", line 310, in get_characters_count
    return len(list(self.get_characters(ignore_blank=ignore_blank)))
  File "C:\Users\User\AppData\Local\Programs\Python\Python310\lib\site-packages\fontbro\font.py", line 272, in get_characters
    char = chr(code)
ValueError: chr() arg not in range(0x110000)
```

**Comment by fabiocaccamo** [comment]
Fixed in `0.14.5` version.
